name: toeic_master_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_naver_map: ^1.4.4
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.4
  table_calendar: ^3.1.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  stomp_dart_client: ^2.0.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/examtalk_logo.png

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"